name: release

on:
  push:
    branches:
      - main

jobs:
  pre_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get plugin version
        id: get_plugin_version
        run: |
          echo "PLUGIN_VERSION=$(cat plugin.yaml | grep "version" | cut -d '"' -f 2)" >> $GITHUB_OUTPUT
          echo "PLUGIN_VERSION=$(cat plugin.yaml | grep "version" | cut -d '"' -f 2)" >> $GITHUB_ENV
      - name: Get tag name
        id: get_tag_name
        run: |
          echo "TAG_NAME=$(echo ${{ github.ref_name }} | cut -d 'v' -f2)" >> $GITHUB_OUTPUT
          echo "TAG_NAME=$(echo ${{ github.ref_name }} | cut -d 'v' -f2)" >> $GITHUB_ENV
    outputs:
      plugin_version: ${{ steps.get_plugin_version.outputs.PLUGIN_VERSION }}
      release_tag: ${{ steps.get_tag_name.outputs.TAG_NAME }}

  bump_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Bump helm versions
        run: sh ./ci/bump-versions.sh
        env:
          APP_VERSION: ${{ needs.pre_release.outputs.release_tag }}
      - name: Test
        run: |
          cat charts/Chart.yaml
          git status
