name: release

on:
  push:
    branches:
      - main

jobs:
  pre_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get plugin version
        id: get_plugin_version
        run: |
          echo "PLUGIN_VERSION=$(cat plugin.yaml | grep "version" | cut -d '"' -f 2)" >> $GITHUB_OUTPUT
          echo "PLUGIN_VERSION=$(cat plugin.yaml | grep "version" | cut -d '"' -f 2)" >> $GITHUB_ENV
      - name: Get tag name
        id: get_tag_name
        run: |
          echo "TAG_NAME=$(echo ${{ github.ref_name }} | cut -d 'v' -f2)" >> $GITHUB_OUTPUT
          echo "TAG_NAME=$(echo ${{ github.ref_name }} | cut -d 'v' -f2)" >> $GITHUB_ENV
    outputs:
      plugin_version: ${{ steps.get_plugin_version.outputs.PLUGIN_VERSION }}
      release_tag: ${{ steps.get_tag_name.outputs.TAG_NAME }}

  bump_versions:
    runs-on: ubuntu-latest
    needs: pre_release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bump helm versions
        run: sh ./ci/bump-versions.sh
        env:
          APP_VERSION: ${{ needs.pre_release.outputs.plugin_version }}
          HELM_CHARTS_SOURCE: "charts/selek"
      # - name: Push helm chart folder
      #   uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.MY_SECRET }}
      #   with:
      #     source_folder: "charts/selek"
      #     destination_repo: "ronahk/helm-test"
      #     destination_folder: "charts/selek"
      #     user_email: "ronahk@komodor.io"
      #     user_name: "ronahk"
      #     commit_msg: "CI: Update selek helm chart"
      #     destination_branch: main
      - name: Push a folder to another repository
        # You may pin to the exact commit or the version.
        # uses: crykn/copy_folder_to_another_repo_action@0282e8b9fef06de92ddcae9fe6cb44df6226646c
        uses: crykn/copy_folder_to_another_repo_action@v1.0.6
        env:
          API_TOKEN_GITHUB: ${{ secrets.MY_SECRET }}
        with:
          # Source folder from the origin directory
          source_folder: "charts/selek"
          # Destination repository
          destination_repo: "ronahk/helm-test"
          # Directory to push the folder contents to
          destination_folder: "charts/selek"
          # Email for the git commit
          user_email: "ronahk@komodor.io"
          # GitHub username for the commit
          user_name: "rona"
          # branch to push folder to, defaults to master
          destination_branch: "main"
          # The commit message
          commit_msg: "Update helm chart"
          # Destination branch to create for this commit
          #destination_branch_create: # optional
